
GET https://api-gateway-demo.deel.network/rest/v1/legal-entities
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQyOTg4NSwicHJvZmlsZUlkIjo0OTgwMzIsIm9yZ2FuaXphdGlvbklkIjoyNjYxOX0.D6o54o0vjnES3vgXPZY5HBYu_Ih2PUFxuxyPw3vp4ebHLyTy1Ku4pcniz2o3RavBiu0sAuowQOd-CpqsWaqYsfQeZFt9tyzWc48LIBuQPZVeNrWUsHsIl9sgW6ewgZmeHLn24DOym3fpqZK_EliTeGtUW87MD5JqRalEoW9Rjl1ylRjWs2uY_TCRTZMGqO713RzUSvbemCZFwjMoTdTUlNpEwHDLz-myhq9GbxFMmmgal7n3I4_XVHd_veGfOErgH6-oCJt-tq1_Fn65mlyK3aOdmi4aSsLA-8DCJ5K0TxS9NleJO_RL5FeFuPgUfioBQEVFMzxFF7rkwmqEoIM5c5ct2AT2XQ9ZZrxFuchIh-SUZo4cKoilJ4kVjNozyWvjfQj3dfohClRI7xW_hYvAjh5OtDB_VjlWLWqOCCFRvmEsBT35D-u7sPtdV25oz25EaTKYhUzejj3wQM04JjmNYfqV6mNKsAd5ycgWfqO99ULbGevLf98uKvZjTDtSZolL


### POST /rest/v1/legal-entities
POST https://api-gateway-demo.deel.network/rest/v1/invoice-adjustments

Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQyOTg4NSwicHJvZmlsZUlkIjo0OTgwMzIsIm9yZ2FuaXphdGlvbklkIjoyNjYxOX0.D6o54o0vjnES3vgXPZY5HBYu_Ih2PUFxuxyPw3vp4ebHLyTy1Ku4pcniz2o3RavBiu0sAuowQOd-CpqsWaqYsfQeZFt9tyzWc48LIBuQPZVeNrWUsHsIl9sgW6ewgZmeHLn24DOym3fpqZK_EliTeGtUW87MD5JqRalEoW9Rjl1ylRjWs2uY_TCRTZMGqO713RzUSvbemCZFwjMoTdTUlNpEwHDLz-myhq9GbxFMmmgal7n3I4_XVHd_veGfOErgH6-oCJt-tq1_Fn65mlyK3aOdmi4aSsLA-8DCJ5K0TxS9NleJO_RL5FeFuPgUfioBQEVFMzxFF7rkwmqEoIM5c5ct2AT2XQ9ZZrxFuchIh-SUZo4cKoilJ4kVjNozyWvjfQj3dfohClRI7xW_hYvAjh5OtDB_VjlWLWqOCCFRvmEsBT35D-u7sPtdV25oz25EaTKYhUzejj3wQM04JjmNYfqV6mNKsAd5ycgWfqO99ULbGevLf98uKvZjTDtSZolL


### GET teams

GET https://api-gateway-demo.deel.network/rest/v1/teams
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQyOTg4NSwicHJvZmlsZUlkIjo0OTgwMzIsIm9yZ2FuaXphdGlvbklkIjoyNjYxOX0.D6o54o0vjnES3vgXPZY5HBYu_Ih2PUFxuxyPw3vp4ebHLyTy1Ku4pcniz2o3RavBiu0sAuowQOd-CpqsWaqYsfQeZFt9tyzWc48LIBuQPZVeNrWUsHsIl9sgW6ewgZmeHLn24DOym3fpqZK_EliTeGtUW87MD5JqRalEoW9Rjl1ylRjWs2uY_TCRTZMGqO713RzUSvbemCZFwjMoTdTUlNpEwHDLz-myhq9GbxFMmmgal7n3I4_XVHd_veGfOErgH6-oCJt-tq1_Fn65mlyK3aOdmi4aSsLA-8DCJ5K0TxS9NleJO_RL5FeFuPgUfioBQEVFMzxFF7rkwmqEoIM5c5ct2AT2XQ9ZZrxFuchIh-SUZo4cKoilJ4kVjNozyWvjfQj3dfohClRI7xW_hYvAjh5OtDB_VjlWLWqOCCFRvmEsBT35D-u7sPtdV25oz25EaTKYhUzejj3wQM04JjmNYfqV6mNKsAd5ycgWfqO99ULbGevLf98uKvZjTDtSZolL
  
###

GET https://api-gateway-demo.deel.network/rest/v1/contracts/32rkrrd
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQyOTg4NSwicHJvZmlsZUlkIjo0OTgwMzIsIm9yZ2FuaXphdGlvbklkIjoyNjYxOX0.D6o54o0vjnES3vgXPZY5HBYu_Ih2PUFxuxyPw3vp4ebHLyTy1Ku4pcniz2o3RavBiu0sAuowQOd-CpqsWaqYsfQeZFt9tyzWc48LIBuQPZVeNrWUsHsIl9sgW6ewgZmeHLn24DOym3fpqZK_EliTeGtUW87MD5JqRalEoW9Rjl1ylRjWs2uY_TCRTZMGqO713RzUSvbemCZFwjMoTdTUlNpEwHDLz-myhq9GbxFMmmgal7n3I4_XVHd_veGfOErgH6-oCJt-tq1_Fn65mlyK3aOdmi4aSsLA-8DCJ5K0TxS9NleJO_RL5FeFuPgUfioBQEVFMzxFF7rkwmqEoIM5c5ct2AT2XQ9ZZrxFuchIh-SUZo4cKoilJ4kVjNozyWvjfQj3dfohClRI7xW_hYvAjh5OtDB_VjlWLWqOCCFRvmEsBT35D-u7sPtdV25oz25EaTKYhUzejj3wQM04JjmNYfqV6mNKsAd5ycgWfqO99ULbGevLf98uKvZjTDtSZolL
 
 
### Contract Query

GET https://api-gateway-demo.deel.network/rest/v1/contracts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQyOTg4NSwicHJvZmlsZUlkIjo0OTgwMzIsIm9yZ2FuaXphdGlvbklkIjoyNjYxOX0.D6o54o0vjnES3vgXPZY5HBYu_Ih2PUFxuxyPw3vp4ebHLyTy1Ku4pcniz2o3RavBiu0sAuowQOd-CpqsWaqYsfQeZFt9tyzWc48LIBuQPZVeNrWUsHsIl9sgW6ewgZmeHLn24DOym3fpqZK_EliTeGtUW87MD5JqRalEoW9Rjl1ylRjWs2uY_TCRTZMGqO713RzUSvbemCZFwjMoTdTUlNpEwHDLz-myhq9GbxFMmmgal7n3I4_XVHd_veGfOErgH6-oCJt-tq1_Fn65mlyK3aOdmi4aSsLA-8DCJ5K0TxS9NleJO_RL5FeFuPgUfioBQEVFMzxFF7rkwmqEoIM5c5ct2AT2XQ9ZZrxFuchIh-SUZo4cKoilJ4kVjNozyWvjfQj3dfohClRI7xW_hYvAjh5OtDB_VjlWLWqOCCFRvmEsBT35D-u7sPtdV25oz25EaTKYhUzejj3wQM04JjmNYfqV6mNKsAd5ycgWfqO99ULbGevLf98uKvZjTDtSZolL
 

### 
GET https://api-gateway-demo.deel.network/rest/v1/lookups/job-titles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQyOTg4NSwicHJvZmlsZUlkIjo0OTgwMzIsIm9yZ2FuaXphdGlvbklkIjoyNjYxOX0.D6o54o0vjnES3vgXPZY5HBYu_Ih2PUFxuxyPw3vp4ebHLyTy1Ku4pcniz2o3RavBiu0sAuowQOd-CpqsWaqYsfQeZFt9tyzWc48LIBuQPZVeNrWUsHsIl9sgW6ewgZmeHLn24DOym3fpqZK_EliTeGtUW87MD5JqRalEoW9Rjl1ylRjWs2uY_TCRTZMGqO713RzUSvbemCZFwjMoTdTUlNpEwHDLz-myhq9GbxFMmmgal7n3I4_XVHd_veGfOErgH6-oCJt-tq1_Fn65mlyK3aOdmi4aSsLA-8DCJ5K0TxS9NleJO_RL5FeFuPgUfioBQEVFMzxFF7rkwmqEoIM5c5ct2AT2XQ9ZZrxFuchIh-SUZo4cKoilJ4kVjNozyWvjfQj3dfohClRI7xW_hYvAjh5OtDB_VjlWLWqOCCFRvmEsBT35D-u7sPtdV25oz25EaTKYhUzejj3wQM04JjmNYfqV6mNKsAd5ycgWfqO99ULbGevLf98uKvZjTDtSZolL
 