
GET https://api-gateway-demo.deel.network/rest/v1/legal-entities
Content-Type: application/json
Authorization: Bearer API_KEY


### POST /rest/v1/legal-entities
POST https://api-gateway-demo.deel.network/rest/v1/invoice-adjustments

Content-Type: application/json
Authorization: Bearer API_KEY


### GET teams

GET https://api-gateway-demo.deel.network/rest/v1/teams
Content-Type: application/json
Authorization: Bearer API_KEY 
###

GET https://api-gateway-demo.deel.network/rest/v1/contracts/32rkrrd
Content-Type: application/json
Authorization: Bearer API_KEY 
 
### Contract Query

GET https://api-gateway-demo.deel.network/rest/v1/contracts
Content-Type: application/json
Authorization: Bearer API_KEY 

### 
GET https://api-gateway-demo.deel.network/rest/v1/lookups/job-titles
Content-Type: application/json
Authorization: Bearer API_KEY 